name: Run ASP.NET API and NUnit Tests

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-test:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore TestApp.sln

    - name: Build the solution
      run: msbuild TestApp.sln /p:Configuration=Release

    - name: Build Docker image
      run: docker build -t TestApp-api -f Dockerfile .

    - name: Start API container
      run: docker run -d -p 8080:80 --name api TestApp-api

    - name: Wait for API to start
      run: |
        $maxRetries = 10
        $retry = 0
        while ($retry -lt $maxRetries) {
          try {
            $response = Invoke-WebRequest https://localhost:44311/api/hello -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "API is up!"
              break
            }
          } catch {
            Write-Host "Waiting for API..."
          }
          Start-Sleep -Seconds 5
          $retry++
        }

    - name: Run NUnit tests
      run: |
        vstest.console.exe TestApp.Tests\bin\Release\TestApp.Tests.dll

    - name: Cleanup Docker container
      if: always()
      run: |
        docker stop api
        docker rm api
